/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.mqtt;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "Mqqt", id = "de.appwerft.mqtt")
public class MqttModule extends KrollModule {
	@Kroll.constant
	public static final int QOS_AT_MOST_ONCE = 0;
	@Kroll.constant
	public static final int QOS_AT_LEAST_ONCE = 1;
	@Kroll.constant
	public static final int QOS_EXACTLY_ONCE = 2;

	public MqttModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

}
